name: Flutter CI

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "stable"

      # Install dependencies
      - name: Install Dependencies
        run: flutter pub get

      # Run Flutter tests
      - name: Run Tests
        run: flutter test

      # Analyze code (optional but recommended)
      - name: Analyze Code
        run: flutter analyze

      # Build the app for debug (ensure it compiles)
      - name: Build for Debug
        run: flutter build apk --debug
